### ISSUE TITLE
Support for customLevels, and useCustomLevels?

### ISSUE THREAD

**Issue by munozu** [pinojs/pino-http#55]
Currently using `pino-http@^4.0.0` as express middleware

```
TypeError: log.error is not a function
    at ServerResponse.onResFinished (/path/to/project/node_modules/pino-http/logger.js:39:11)
    at emitNone (events.js:111:20)
    at ServerResponse.emit (events.js:208:7)
    at onFinish (_http_outgoing.js:723:10)
    at onCorkedFinish (_stream_writable.js:629:5)
    at afterWrite (_stream_writable.js:454:3)
    at _combinedTickCallback (internal/process/next_tick.js:144:20)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

https://github.com/pinojs/pino/blob/master/docs/api.md#useonlycustomlevels-boolean
```
// usage example
const logger = pino({
  customLevels: {
    foo: 35
  },
  useOnlyCustomLevels: true,
  level: 'foo'
})
logger.foo('hi')
logger.info('hello') // Will throw an error saying info in not found in logger object
```

**Comment by mcollina** [comment]
Of course, it can't find the level `error` as `useOnlyCustomLevels`  is set to `true`. It is the exact meaning of that option.

What behavior would you expect here?

**Comment by munozu** [comment]
I figured it out, was wrong on my end 😅thanks for the quick response!
